# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      - system:masters
      rolearn: arn:aws:iam::417747745715:role/UdacityFlaskDeployCBKubectlRole
      username: Udacity	
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-19T05:28:03Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1381"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 2dce6711-9d73-4a21-b895-69329960c7d8
