apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::417747745715:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-HVRTKF9YFQ22
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::417747745715:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-03-08T11:28:05Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-03-08T11:28:05Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1374"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 9c32f6c4-5726-41ca-aaab-ee9b3d8c24c8
